export const gameData = [
    { year: 2003, name: "Stack Attack" },
    { year: 2004, name: "FIRST Frenzy: Raising the Bar" },
    { year: 2005, name: "Triple Play" },
    { year: 2006, name: "Aim High" },
    { year: 2007, name: "Rack 'n Roll" },
    { year: 2008, name: "FIRST Overdrive" },
    { year: 2009, name: "Lunacy" },
    { year: 2010, name: "Breakaway" },
    { year: 2011, name: "Logo Motion" },
    { year: 2012, name: "Rebound Rumble" },
    { year: 2013, name: "Ultimate Ascent" },
    { year: 2014, name: "Aerial Assist" },
    { year: 2015, name: "Recycle Rush" },
    { year: 2016, name: "FIRST Stronghold" },
    { year: 2017, name: "FIRST Steamworks" },
    { year: 2018, name: "FIRST Power Up" },
    { year: 2019, name: "Destination: Deep Space" },
    { year: 2020, name: "Infinite Recharge" },
    { year: 2021, name: "Infinite Recharge at Home" },
    { year: 2022, name: "Rapid React" },
    { year: 2023, name: "Charged Up" },
  ];